// config/paymentButtons.default.js (or anywhere you prefer)
module.exports = [
  {
    key: "pay_entry",
    enabled: false,
    title: "Pay Entry",
    description: "Door entry for tonight’s show",
    pricingMode: "min",
    fixedAmount: null,
    minAmount: 5,
    presetAmounts: [],
    badgeId: "show_supporter",
    shareEnabled: true,
    supporterWallEligible: true,
    unlockEnabled: false,
  },
  {
    key: "tip_band",
    enabled: false,
    title: "Tip the Band",
    description: "Thanks for the support ❤️",
    pricingMode: "min",
    fixedAmount: null,
    minAmount: 5,
    presetAmounts: [],
    badgeId: "tip_legend",
    shareEnabled: true,
    supporterWallEligible: true,
    unlockEnabled: false,
  },
  {
    key: "pay_merch",
    enabled: false,
    title: "Pay for Merch",
    description: "Shirts, posters, vinyl, etc.",
    pricingMode: "min",
    fixedAmount: null,
    minAmount: 5,
    presetAmounts: [],
    badgeId: "merch_mvp",
    shareEnabled: true,
    supporterWallEligible: true,
    unlockEnabled: false,
  },
  {
    key: "support_band",
    enabled: false,
    title: "Support the Band",
    description: "Help us keep making music",
    pricingMode: "min",
    fixedAmount: null,
    minAmount: 5,
    presetAmounts: [],
    badgeId: "band_backer",
    shareEnabled: true,
    supporterWallEligible: true,
    unlockEnabled: false,
  },
  {
    key: "help_get_home",
    enabled: false,
    title: "Help Us Get Home",
    description: "Gas, food, and late nights on the road",
    pricingMode: "min",
    fixedAmount: null,
    minAmount: 5,
    presetAmounts: [],
    badgeId: "road_crew",
    shareEnabled: true,
    supporterWallEligible: true,
    unlockEnabled: false,
  },
  {
    key: "after_show_support",
    enabled: false,
    title: "After-Show Support",
    description: "Thanks for coming out tonight ❤️",
    pricingMode: "min",
    fixedAmount: null,
    minAmount: 5,
    presetAmounts: [],
    badgeId: "after_show_backer",
    shareEnabled: true,
    supporterWallEligible: true,
    unlockEnabled: false,
  },
];
